[package]
name = "tc"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
codegen-units = 1
strip = true
debug = false
incremental = false

[dependencies]
crossterm = "0.28.1"
linefeed = "0.6.0"
once_cell = "1.21.1"
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", default-features = false, features = ["macros", "rt-multi-thread", "time"] }
