[package]
name = "tc"
version = "0.1.0"
edition = "2024"

[profile.release]
panic = "abort"
lto = true
opt-level = 'z'
codegen-units = 1
strip = true
debug = false
incremental = false

[dependencies]
crossterm = { version = "0.28.1", default-features = false }
futures-util = { version = "0.3.31", default-features = false }
linefeed = { version = "0.6.0", default-features = false }
once_cell = { version = "1.21.1", default-features = false }
reqwest = { version = "0.12.12", default-features = false, features = ["json", "rustls-tls", "stream"] }
serde = { version = "1.0.219", default-features = false, features = ["derive"] }
serde_json = { version = "1.0.140", default-features = false }
tokio = { version = "1.44.0", default-features = false, features = ["macros", "rt-multi-thread"] }
walkdir = { version = "2.5.0", default-features = false }
