[package]
name = "terminal_chat"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.12"
rustyline = "15.0.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["full"] }
