[package]
name = "tc"
version = "0.1.0"
edition = "2024"

[dependencies]
linefeed = "0.6.0"
once_cell = "1.21.1"
reqwest = "0.12.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tokio = { version = "1.44.0", features = ["full"] }
